### ISSUE TITLE
[!] python-socketio[client] version 5.7.2 NOT installed.

### ISSUE THREAD

**Issue by sashaok123** [civitai/sd_civitai_extension#10]
When Automatic1111 is started, a warning is issued: 
**[!] python-socketio[client] version 5.7.2 NOT installed.**
<img width="731" alt="image" src="https://user-images.githubusercontent.com/27728380/221373110-7c075345-4739-45f9-9c80-488115530e7a.png">

**Comment by JustMaier** [comment]
Yeah, I couldn't seem to get the install check to work consistently. I bet the package is installed but it's not detecting it correctly.

At least until Civitai Link is released, the SocketIO connection isn't needed for any of the current extension functionality.

**Comment by mammour** [comment]
I met this error too,

tried installing python-socketio in venv but it didn't work 

**But this worked (out of venv)**

`cd INSERT_PATH_TO_AU1111` (Or directly open your console in Automatic1111 UI root folder)

` cd extensions\sd_civitai_extension\` 

` pip install -r requirements.txt`

**Comment by JustMaier** [comment]
The [install script](https://github.com/civitai/sd_civitai_extension/blob/main/install.py) should handle automatically installing the requirements of the extension, in my experience, it seems like its possible that the warning is just not correctly detecting the installed package.

**Comment by moahegg** [comment]
Got the error also, but as is often the case just completely exiting A1111 and starting it again worked.

**Comment by OneLittleWolf** [comment]
> pip install -r requirements.txt

Thanks! This fixed it for me too.

**Comment by antv311** [comment]
> I met this error too,
> 
> tried installing python-socketio in venv but it didn't work
> 
> **But this worked (out of venv)**
> 
> `cd INSERT_PATH_TO_AU1111` (Or directly open your console in Automatic1111 UI root folder)
> 
> ` cd extensions\sd_civitai_extension\`
> 
> ` pip install -r requirements.txt`

yeah this does the trick
