### ISSUE TITLE
Dependency install conflict `launch` version

### ISSUE THREAD

**Issue by shaneholloman** [civitai/sd_civitai_extension#13]
Looks like it could be my problem. Mentioning in case some else ran into this

Path: `E:\ai\sd\stable-diffusion-webui\extensions\sd_civitai_extension`

![image](https://user-images.githubusercontent.com/1563909/221869984-4fb0e58c-688f-47f5-933c-4a175127f3db.png)

**Comment by JustMaier** [comment]
The install script is something that is intended to be automatically run by the SD Web UI.
I recommend removing the extension from your extensions folder and following [the instructions we just added](https://github.com/civitai/sd_civitai_extension#through-the-extensions-ui-recommended) about installing it through the SD UI.

Let me know if you still have this problem after doing that :)

**Comment by JustMaier** [comment]
I'll assume you've got this resolved. If you do end up still needing help here, feel free to re-open the issue 👍

**Comment by jiyuren** [comment]
modify you install.py insert sys.path.append('../YOUR_PATH') the launch module is your launch.py just import it
