### ISSUE TITLE
incorrect preview image downloaded for "sd-v1-4.ckpt [fe4efff1e1]"

### ISSUE THREAD

**Issue by azumukupoe** [civitai/sd_civitai_extension#16]
[this image](https://imagecache.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/0e46a1c9-95db-4baf-6a93-62f6222c6600/width=450) is gets downloaded for "sd-v1-4.ckpt [fe4efff1e1]" which doesn't seem right

**Comment by JustMaier** [comment]
Looks like someone had uploaded the sd 1.4 model under a different name. It's now been unpublished.
