### ISSUE TITLE
Hash matching relies on unchanged filenames

### ISSUE THREAD

**Issue by Zetaphor** [civitai/sd_civitai_extension#19]
I'm looking through the code so I could query the API for my own purposes and I noticed the hashing mechanism relies on the filename being exactly the same as what the asset uploader used. This means if I rename any of my files they will no longer have matching hashes.

This seems like bad behavior and partly defeats the purpose of using hashes

**Comment by Zetaphor** [comment]
Line in question:

https://github.com/civitai/sd_civitai_extension/blob/b72f6d93ec8441d8f73345d8f072c05f24620190/civitai/lib.py#L174

**Comment by scruffynerf** [comment]
Seconded.

Either you use file contents or partial file contents.
Not filename.

If metadata stored in inside a file changes the contents (mp4 comes to mind, or pnginfo, etc) that's a problem but filename shouldn't matter for hash identification.

**Comment by Zetaphor** [comment]
This appears to have been a misunderstanding on my part as well as an actual bug. 

The misunderstanding was that the API doesn't rely on the filenames and paths.

The actual bug was the API hashing algorithm was case sensitive, assuming uppercase A-Z while my hashing method was producing lowercase a-z. An update is being pushed to the API and so this issue can be closed
