### ISSUE TITLE
Since this is testing does that explain why the tab in automatic1111 is gone

### ISSUE THREAD

**Issue by shaneholloman** [civitai/sd_civitai_extension#2]
Hours manually handling assets, previews etc - this will be a welcome addition!

**Comment by runner22k** [comment]
Same here, I don't see the tab in SD WebUI.

**Comment by shaneholloman** [comment]
```python
#######################################################################################################
Initializing Civitai Link
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Civitai Link revision: 245769f4ea1d9296f8e8e24d90ec6facd4b16f38
SD-WebUI revision: ea9bd9fc7409109adcd61b897abc2c8881161256

Checking Civitai Link requirements...
[!] socketio[client] NOT installed.
[+] blake3 version 0.3.3 installed.

#######################################################################################################
```

**Comment by shaneholloman** [comment]
what version of socketio do we need
And can I system install, or does it have to be installed into the venv?

**Comment by shaneholloman** [comment]
duh, sorry found this `https://github.com/civitai/sd_civitai_extension/blob/main/requirements.txt` lets see if it works now

**Comment by runner22k** [comment]
> ```python
> #######################################################################################################
> Initializing Civitai Link
> If submitting an issue on github, please provide the below text for debugging purposes:
> 
> Python revision: 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
> Civitai Link revision: 245769f4ea1d9296f8e8e24d90ec6facd4b16f38
> SD-WebUI revision: ea9bd9fc7409109adcd61b897abc2c8881161256
> 
> Checking Civitai Link requirements...
> [!] socketio[client] NOT installed.
> [+] blake3 version 0.3.3 installed.
> 
> #######################################################################################################
> ```

I don't get such message? How to get it?

**Comment by shaneholloman** [comment]
remember this is not ready for use. that said if you have the latest version installed you will see this in the console during startup. Latest version shows this now (which is different to above)

```python
#######################################################################################################
Initializing Civitai Link
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Civitai Link revision: 5c8b310c71dd7632fc2e4a1d113b06c4cc377cd3
SD-WebUI revision: ea9bd9fc7409109adcd61b897abc2c8881161256

Checking Civitai Link requirements...
[+] python-socketio[client] version 5.7.2 installed.

#######################################################################################################
```
