### ISSUE TITLE
plugin provides message

### ISSUE THREAD

**Issue by HinxVietti** [civitai/sd_civitai_extension#29]
Initializing Civitai Link
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
Civitai Link revision: 579d6940168230daf0d32a1c936c0dd0ba27b433
SD-WebUI revision: 66cfd1dcfc893a9051310c208a66890b86334118

Checking Civitai Link requirements...
[!] python-socketio[client] version 5.7.2 NOT installed.

**Comment by McFex** [comment]
Where exactly do I execute the above?
In the extension folder or in the main web-ui folder?

**Comment by HinxVietti** [comment]
> Where exactly do I execute the above? In the extension folder or in the main web-ui folder?

execute it before you running webui, it should be install to your compute, no matter what folder you chosed.
