### ISSUE TITLE
Showing download progress within UI with the possibility to stop/cancel a current download

### ISSUE THREAD

**Issue by Alyndiar** [civitai/sd_civitai_extension#3]
Hi,

No idea if this is feasable. It would be nice to have a listbox with the downloading models/files status and completion percentages, as well as the option to cancel a currently downloading file. I guess a clear button would also be needed to clear all completed downloads.

**Comment by JustMaier** [comment]
As part of Civitai Link (coming soon), you will be able to see the progress of download from the site as you browse and from the console.
