### ISSUE TITLE
Civitai: Found 624 resources missing preview images Civitai: Found 3 hash matches Civitai: Updated 0 preview images

### ISSUE THREAD

**Issue by DarksealStudios** [civitai/sd_civitai_extension#53]
Civitai: Found 624 resources missing preview images
Civitai: Found 3 hash matches
Civitai: Updated 0 preview images

Why won't this thing update my images? There used to be a tab but now I just see an icon in the corner. How do I turn this thing on? I've installed it for sure, I install the requirement too. HALP?!

**Comment by hoodady** [comment]
Civitai: Found 393 resources missing preview images
Civitai: Found 345 hash matches
Civitai: Updated 0 preview images

got the same problem

**Comment by DarksealStudios** [comment]
Hoodady, it was the wrong extension, got a different one than this and it works fine, has helper in the name i think

**Comment by SouthbayJay** [comment]
Do you happen to have a link to the correct extension?

**Comment by DarksealStudios** [comment]
https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper
