### ISSUE TITLE
Handshake error when adding link key

### ISSUE THREAD

**Issue by smileynet** [civitai/sd_civitai_extension#65]
Using latest version, running on Ubuntu Jammy, I get this error when trying to add the link key:

16:37:16-901399 ERROR    changing setting civitai_link_key to 8868e0: KeyError
╭───────────────────────────── Traceback (most recent call last) ─────────────────────────────╮
│ /home/sam/automatic/modules/shared.py:526 in set                                            │
│                                                                                             │
│   525 │   │   │   try:                                                                      │
│ ❱ 526 │   │   │   │   self.data_labels[key].onchange()                                      │
│   527 │   │   │   except Exception as e:                                                    │
│                                                                                             │
│ /home/sam/automatic/extensions/sd_civitai_extension/civitai/link.py:228 in                  │
│ on_civitai_link_key_changed                                                                 │
│                                                                                             │
│   227 │                                                                                     │
│ ❱ 228 │   if not sio.connected: socketio_connect()                                          │
│   229                                                                                       │
│                                                                                             │
│                                   ... 7 frames hidden ...                                   │
│                                                                                             │
│ /home/sam/automatic/venv/lib/python3.10/site-packages/websocket/_handshake.py:57 in         │
│ handshake                                                                                   │
│                                                                                             │
│    56 │                                                                                     │
│ ❱  57 │   status, resp = _get_resp_headers(sock)                                            │
│    58 │   if status in SUPPORTED_REDIRECT_STATUSES:                                         │
│                                                                                             │
│ /home/sam/automatic/venv/lib/python3.10/site-packages/websocket/_handshake.py:147 in        │
│ _get_resp_headers                                                                           │
│                                                                                             │
│   146 │   if status not in success_statuses:                                                │
│ ❱ 147 │   │   response_body = sock.recv(int(resp_headers['content-length']))  # read the bo │
│   148 │   │   raise WebSocketBadStatusException("Handshake status {status} {message} -+-+-  │
╰─────────────────────────────────────────────────────────────────────────────────────────────╯
KeyError: 'content-length'

**Comment by JustMaier** [comment]
Thanks for the report. Was it working for you previously?

**Comment by smileynet** [comment]
I've had it working in a different environment (win11), but this was my first attempt on this box.

**Comment by bryanimplus** [comment]
same issue , working in macOS

**Comment by JustMaier** [comment]
@koenbeuk who's a part of our core dev team is able to reproduce this issue and is actively working on it.

**Comment by koenbeuk** [comment]
@smileynet @bryanimplus Can you still reproduce this issue using the latest version of this extension?

**Comment by bryanimplus** [comment]
thanks guys , its working well with latest versions.

**Comment by koenbeuk** [comment]
Great!
