### ISSUE TITLE
CivitAI Link Not Connecting?? 

### ISSUE THREAD

**Issue by SouthbayJay** [civitai/sd_civitai_extension#87]
For the last few days my A1111 has not been able to connect to the CivitAI website and yesterday my connections that are usually shown on the CivitAI website are gone. I've been trying to create a new key but its just hanging on "generating key" 

Is this due to the host change? Looking on Discord seems like I'm not the only having the issue but I haven't seen anyone address any of the posts. Here is my debugging text below. 

If it is because of the host change it's totally understandable, just a heads up would be great!

#######################################################################################################
Initializing Civitai Link
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Civitai Link revision: 2dfc03c17304278ca0b456366cc7871a2af8377b
SD-WebUI revision: baf6946e06249c5af9851c60171692c44ef633e0

Checking Civitai Link requirements...
[!] python-socketio[client] version 5.7.2 NOT installed.

#######################################################################################################

**Comment by Cornmeister** [comment]
#86
